import streamlit as st


def load_view():
    st.markdown("# Team 40's Submission for *DO YOU HAVE THE GUTS? 2022*")
    st.markdown("Our team members are Robert Nimmo, Franciszek Sowul, James Sharma, and Brandon Forrest. You can view our source files, or information about the challenge brief, on the [GitHub Page](https://github.com/JamesSharma04/DYHTG-22). Feel free to browse our navbar to look around at our submission, or keep reading for an explanation of each page, and a summary of our findings.")
    st.markdown("## Map Timeline")
    st.markdown("On the map, student location data is presented. They marked with dots, and are shown moving around the map with linear interpolation between buildings.")
    st.markdown("The map also shows relevant campus buildings, which are marked with a lightbulb according to their opening times.")
    st.markdown("## Information about Students with Testimonies")
    st.markdown("This page gives information about each student who wrote a testimony. You can view a list of these students in the sidebar of the page. ")
    st.markdown("### Artist's Sketch of the Subject")
    st.markdown("For each student, an AI-generated image is shown. This can be interpreted as a sketch by security guards and estimators, but is really just fed into the replicate API with age, sex, subject, and hair colour as the prompt. Some of the results are quite funny. ")
    st.markdown("### Natural Language Description")
    st.markdown("We have used the data from the spreadsheets to provide each student's information, including the societies they frequent in an english sentence. ")
    st.markdown("### Testimony ")
    st.markdown("We have extracted each student's testimony and displayed it. Buildings and some subjects mentioned are highlighted. This is particularly useful in the case of abbreviations, or when matching up their testimony with their location data. ")
    st.markdown("### Discrepancy Venn Diagram")
    st.markdown("This will display if a student's testimony and their security data does not match up. It allows for easy visualisation, allowing it to be deduced quickly if a student said they went somewhere they in fact did not, or did not mention a place where they in fact did go.")
    st.markdown("### Security Log Timeline")
    st.markdown("This section visualies each student's security log data, showing which buildings they were in and when. It shows up in red if a student was in a building not mentioned in their testimony, or if they were inside a building past its closing time. ")
    st.markdown("## Information about Students without Testimonies")
    st.markdown("This shows students who have no testimony. It gives an AI-Generated sketch of the person, a sentence summary about them, and a timeline of their security log. ")
    st.markdown("## People Data Analysis")
    st.markdown("This page shows a couple of histograms, showing the distribution of ages and heights. In the case of age, we have highlighted suspicious outliers, including those under 18, and those above 30. ")
    st.markdown("# Suspicious Findings")
    st.markdown("Abdul Murphy - In boyd orr after closing")
    st.markdown("Oscar Brown - Overlapping security data timeline, evasive testimony")
    st.markdown("Alice Patterson - Went to the Boyd Orr Building but neglected to mention it in her destimony. Overlapping security data timeline")
    st.markdown("Stuart Wands - 17 and went to Hive")
    st.markdown("")